---
- name: Ensure sysctl.d exists
  become: true
  ansible.builtin.file:
    path: /etc/sysctl.d
    state: directory
    mode: "0755"

- name: Place sysctl config file
  become: true
  ansible.builtin.copy:
    src: 90-syncthing.conf
    dest: /etc/sysctl.d/90-syncthing.conf
    mode: "0644"
    backup: true
  notify: Reload sysctl

- name: Download Syncthing tarball
  ansible.builtin.get_url:
    url: "{{ syncthing_url }}"
    dest: /tmp/syncthing.tar.gz
    mode: "0644"

- name: Ensure temp directory exists
  ansible.builtin.file:
    path: /tmp/syncthing
    state: directory
    mode: "0755"

- name: Extract Syncthing tarball
  ansible.builtin.unarchive:
    src: /tmp/syncthing.tar.gz
    dest: /tmp/syncthing
    remote_src: true
    creates: /tmp/syncthing/syncthing
    extra_opts:
      - --strip-components=1

- name: Copy syncthing executable
  become: true
  ansible.builtin.copy:
    src: /tmp/syncthing/syncthing
    dest: /usr/bin/syncthing
    mode: "0755"
    remote_src: true
    owner: root
    group: root

- name: Copy syncthing systemd units
  become: true
  ansible.builtin.copy:
    src: "/tmp/syncthing/etc/linux-systemd/system/{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
    remote_src: true
    owner: root
    group: root
  loop:
    - syncthing@.service
    - syncthing-resume.service
  register: syncthing_systemd_units

- name: Enable syncthing-resume.service
  become: true
  ansible.builtin.systemd:
    daemon_reload: "{{ syncthing_systemd_units.results[0].changed | bool or syncthing_systemd_units.results[1].changed | bool }}"
    name: syncthing-resume
    enabled: true

- name: Configure firewall settings for Syncthing
  when: syncthing_configure_firewall
  ansible.builtin.include_tasks: setup/firewall.yml

- name: User specific tasks
  when: syncthing_install_user
  ansible.builtin.include_tasks: setup/user.yml

- name: Configure syncthing for user
  when: syncthing_install_user and syncthing_configure
  ansible.builtin.include_tasks: setup/configure.yml

- name: Start syncthing for user
  become: true
  become_user: "{{ syncthing_user }}"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
    name: syncthing
    state: started
    enabled: true
  when: syncthing_install_user

...
