---
- name: Ensure sysctl.d exists
  become: true
  ansible.builtin.file:
    path: /etc/sysctl.d
    state: directory
    mode: "0755"

- name: Place sysctl config file
  become: true
  ansible.builtin.copy:
    src: 90-syncthing.conf
    dest: /etc/sysctl.d/90-syncthing.conf
    mode: "0644"
    backup: true
  notify: Reload sysctl

- name: Download Syncthing tarball
  ansible.builtin.get_url:
    url: "{{ syncthing_url }}"
    dest: /tmp/syncthing.tar.gz
    mode: "0644"

- name: Ensure temp directory exists
  ansible.builtin.file:
    path: /tmp/syncthing
    state: directory
    mode: "0755"

- name: Extract Syncthing tarball
  ansible.builtin.unarchive:
    src: /tmp/syncthing.tar.gz
    dest: /tmp/syncthing
    remote_src: true
    creates: /tmp/syncthing/syncthing
    extra_opts:
      - --strip-components=1

- name: Copy syncthing executable
  become: true
  ansible.builtin.copy:
    src: /tmp/syncthing/syncthing
    dest: /usr/bin/syncthing
    mode: "0755"
    remote_src: true
    owner: root
    group: root
  register: copy_syncthing_exec
  changed_when: "copy_syncthing_exec is changed and 'molecule-idempotence-notest' not in ansible_skip_tags" # Rotating keys

- name: Copy syncthing systemd units
  become: true
  ansible.builtin.copy:
    src: "/tmp/syncthing/etc/linux-systemd/system/{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
    remote_src: true
    owner: root
    group: root
  loop:
    - syncthing@.service
    - syncthing-resume.service
  register: syncthing_systemd_units

...
