---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    # Prevent Apt cache errors
    - name: "Refresh Apt cache"
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts["pkg_mgr"] == "apt"
      changed_when: false # Breaks idempotency test

    # https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
    - name: Wait for systemd to complete initialization. # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts["service_mgr"] == 'systemd'
      changed_when: false
      failed_when: false

  tasks:
    - name: "Include diademiemi.syncthing"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

...
