---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.

name: Import to Galaxy

'on':
  workflow_run:
    workflows: ['Molecule Test']
    types: ["completed"]

jobs:
  galaxy-import:
    name: Import to Galaxy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)

...
