---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: UFW tasks
  when:
    - ansible_facts.services is defined
    - "'ufw' in ansible_facts.services"
    - ansible_facts.services['ufw'].state == 'started'
  block:
    - name: Copy over UFW application config
      become: true
      ansible.builtin.copy:
        src: /tmp/syncthing/etc/firewall-ufw/syncthing
        dest: /etc/ufw/applications.d/syncthing
        mode: "0644"
        remote_src: true
        owner: root
        group: root

    - name: Allow syncthing with UFW
      become: true
      community.general.ufw:
        rule: allow
        name: syncthing

- name: Allow Syncthing ports with firewalld
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    zone: public
  loop:
    - 22000/tcp
    - 21027/udp
  when:
    - ansible_facts.services is defined
    - "'firewalld' in ansible_facts.services"
    - ansible_facts.services['firewalld'].state == 'started'

...
